# Generated by Django 5.0.6 on 2024-06-20 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='This is a normal task', max_length=600),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 8, 17, 49, 433597, tzinfo=datetime.timezone.utc)),
        ),
    ]
