# Generated by Django 5.0.6 on 2024-06-20 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_task_description_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 12, 13, 59, 900297, tzinfo=datetime.timezone.utc)),
        ),
    ]
